env: "local" # local, dev, prod
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "test"
  password: "test"
database_data:
  host: "localhost"
  port: 5432
  user: "test"
  password: "test"
